name: "错误报告"
description: "破损或不正确的行为"
labels: [unconfirmed bug]
body:
  - type: markdown
    attributes:
      value: >
        谢谢你花时间来填写一个错误。
        请注意，这个表格只适用于错误报告!
  - type: input
    id: intro
    attributes:
      label: "摘要"
      description: "你的错误报告的简单摘要"
    validations:
      required: true
  - type: textarea
    id: reproduce_step
    attributes:
      label: "复现步骤"
      description: >
         你做了什么来发现这个错误。
    validations:
      required: true
  - type: textarea
    id: reproduce_code
    attributes:
      label: "最小的复现代码"
      description: >
        一个展示了这个错误的代码片段。
      render: golang
  - type: textarea
    id: expected_result
    attributes:
      label: "预期结果"
      description: >
        你预计会发生什么？
    validations:
      required: true
  - type: textarea
    id: actual_result
    attributes:
      label: "实际结果"
      description: >
        实际上发生了什么？
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: "额外背景"
      description: "如果还有什么要说的，请在这里说。"