name: test
on:
  - issue_comment
jobs:
  create_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        go-version:
          - "1.18"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: ^/test\s*(.*?)\s*$
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            A test action on ${{ steps.regex-match.outputs.group1 }} is triggered.
            - You can view thr run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
            - Created by [test-action](https://github.com/foxwhite25/megaCrawler/blob/master/.github/workflows/test.yml).
          reactions: '+1'
      - name: Setup Go
        uses: actions/setup-go@v3
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set ENV
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: echo "TARGET=${{ steps.regex-match.outputs.group1 }}" >> $GITHUB_ENV
      - name: Install dependencies
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: go get .
      - name: Test with Go
        id: test
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: go test > RunResult.txt
      - name: Upload Go log
        uses: actions/upload-artifact@v3
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          name: Go-log-${{ matrix.go-version }}
          path: ./log/debug.jsonl
      - name: Upload Go Result
        uses: actions/upload-artifact@v3
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          name: Go-result-${{ matrix.go-version }}
          path: RunResult.txt