name: test
on:
  - issue_comment
jobs:
  create_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        go-version:
          - "1.18"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: ^/test\s*(.*?)\s*$
      - name: Create comment
        id: create_comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            A test action on ${{ steps.regex-match.outputs.group1 }} is triggered.
            - You can view the run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
            - Created by [test-action](https://github.com/foxwhite25/megaCrawler/blob/master/.github/workflows/test.yml).
          reactions: '+1'
      - name: Setup Go
        uses: actions/setup-go@v3
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set ENV
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: echo "TARGET=${{ steps.regex-match.outputs.group1 }}" >> $GITHUB_ENV
      - name: Install dependencies
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: go get .
      - name: Test with Go
        id: test
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: go test
      - name: Get File into OUTPUT
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: |
          echo 'RESULT<<EOF' >> $GITHUB_ENV
          cat ./log/debug.jsonl >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Update comment
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.create_comment.outputs.comment-id }}
          body: |
            The run on ${{ steps.regex-match.outputs.group1 }} has finished.
            - You can view the run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
            - Created by [test-action](https://github.com/foxwhite25/megaCrawler/blob/master/.github/workflows/test.yml).
            
            <details>
              <summary>Result</summary>
            
              ```yaml
              ${{ env.RESULT }}
              ```
            </details>
